version: '2'
services:
  pgtap:
    image: geometalab/postgres-pgtap
    build:
      context: .
      dockerfile: Dockerfile
  pgtap_test:
    image: geometalab/postgres-pgtap
    links:
      - "pgtap:postgres"
    # command: bash -c "pg_prove --failures --formatter TAP::Formatter::File -U postgres -h postgres /examples/01-tests/*.sql > /examples/01-tests/test_results.txt"
    command: bash -c "(cd /examples/angproj/user_uploads;unzip -d /tmp/user_uploads *.zip;cd /tmp/user_uploads;psql -U postgres -h postgres -f 0_runAllScripts.sql);psql --username postgres -d angproj -c 'CREATE EXTENSION pgtap;';pg_prove --failures -U postgres -h postgres -d angproj /examples/angproj/01-tests/*.sql"
    environment:
      - PGHOST=postgres
    volumes:
      - ./examples:/examples
